### ISSUE TITLE
networkX was required for installation

### ISSUE THREAD

**Issue by Alexander-Schiendorfer** [ChrislS/fertilized-forests#14]
FYI, to make this part of the prerequisites work:

# Install Python dependencies.
sudo pip install jinja2 cppheaderparser pillow \
  scikit-image matplotlib scikit-lear

I needed to call 

sudo pip install networkx 

first

**Comment by ChrislS** [comment]
Thank you for the remark! The instructions are updated on the homepage already, and I adjusted the README.MD also accordingly (which will be visible with the next merge from unstable to master).
