### ISSUE TITLE
Problem with DLL import on Windows

### ISSUE THREAD

**Issue by Alexander-Schiendorfer** [ChrislS/fertilized-forests#20]
Hi all,

I'm trying to use the windows binaries and followed the instructions (downloaded the zip and executed python setup.py install in the pyfertilized folder) but now I'm stuck with the error message

"    import pyfertilized as _pyfertilized
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden."

Do you recognize that issue?

Best,
Alex

**Comment by ChrislS** [comment]
I do recognize the error message, however all required DLL libraries should be included in the download. I'm just working on the v1 release binaries, so in a few days a new version should be out. The currently available one for Windows is not archive compatible to the Linux and most recent Windows one. It would be great, however, to know which DLL is missing.

To diagnose this, you can download the [dependency walker](http://dependencywalker.com/). It's a directly executable file, no need to install. When you open the program, you can open the file 'fertilized.pyd' in the pyfertilized folder and see what dependencies are missing. It would be great if you could report back...

Thanks!
Christoph

**Comment by Alexander-Schiendorfer** [comment]
Hi Christoph,

thanks for your reply. Your tool suggestion indeed helped me to figure out the issue.
I was missing a visual studio installation on my workers as well as the 

Visual C++ Redistributable for Visual Studio 2012 Update 4

which, upon installation, resolved the issue.

https://www.microsoft.com/en-us/download/details.aspx?id=30679

Cheers,
Alex

**Comment by ChrislS** [comment]
A Visual Studio installation should not be necessary, but the _Visual C++ redistributable for Visual Studio 2012 Update 4_ makes sense.

Could you confirm that installing the redistributable is sufficient? In that case, I'll close the issue and add the info to the guides...

**Comment by Alexander-Schiendorfer** [comment]
that's right, I only installed the redistributables and it worked like a charm!

**Comment by ChrislS** [comment]
Perfect, thanks for the update! I'll add this info to the guides.
